name: Update README

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        run: |
          curl -o README.md https://raw.githubusercontent.com/hasti522004/hasti522004/main/README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README"
          git push
